### ISSUE TITLE
Create a react-ecsal layer

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#101]
# Description
Let's create a react-ecs layer inspired by Redux and [Zustand](https://github.com/react-spring/zustand), and possibly GraphQL syntax. Zustand in particular has tiny source code and has some patterns we're interested in. Let's see how to create a similar selector/hook system that plugs into ECS.

Consider:
- Redux and Zustand dispatch on every store change -- we can optimize by batching all updates in a frame so that the engine notifies react-ecs when it's finished processing a frame and then the store change is triggered (checks all selectors if their output changed, and if so calls the listener with the new state).
    - ReactDOM seems to have an unstable_batch api
- Pseudoimmutability: Let's try adding an "last updated on frame" field to NComponent that react-ecs can use to check if something has updated. ComponentManager can return components with proxies that update the "last updated on frame" if the setter is called.
- Certain systems or consumers of said systems that constantly update could set a flag that indicates they should not bother diffing and just update every frame?

## Acceptance Criteria

# Tasks
```
Use this section to keep track of work
```
- [x] Set up Provider context
- [x] Create context hooks
- [x] Create useSelector
- [x] Create useDispatch
- [x] Create Subscription class
- [x] Create other necessary functions
- [x] Consider dispatching directly to the Router and skipping the APIClient

# QA Notes
