### ISSUE TITLE
Allow player to equip items

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#105]
# Description
Let's allow the player to equip items from their inventory. They should also be able to unequip them and see equipped items. This will involve creating 

## Acceptance Criteria

# Tasks
```
Use this section to keep track of work
```
- [ ] Create necessary components for equipment and the equipment section of the inventory (depending on design in #103)
- [ ] Create a system to handle equipping and unequipping items
- [ ] Create a controller to handle equipping and unequipping items
- [ ] Hook up the player's inventory to dispatch correct actions
- [ ] Hook up the player's inventory to display equipment

# QA Notes

**Comment by nmkataoka** [comment]
Moving this out of the milestone because I think some engine updates are in order.
