### ISSUE TITLE
Create ItemStackCmpt and refactor existing item code

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#109]
# Description
Let's create a fresh `ItemStackCmpt` and fix up all the downstream usages of items. This will mean there is no `ItemCmpt`.

ItemStackCmpt design:
- stackCount
- material (maybe just a direct reference? NO use id! Let's avoid "pointer" like references as much as possible)
- itemClass
- publicSalePrice
- health

### Dependencies
Requires: #107, #108

## Acceptance Criteria

# Tasks
```
Use this section to keep track of work
```
- [x] create ItemStackCmpt
- [x] update InventoryCmp to use ItemStackCmpt 
- [x] update any controllers and systems
- [x] update the frontend api Info types
- [x] update frontend redux and how it's used in the React components
- [x] create helper on EntityManager to access DataDbCmpts in fewer lines of code
- [x] update the item creator functions in the engine start

# QA Notes
