### ISSUE TITLE
Set up absolute path imports

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#113]
# Description
Let's set up absolute path imports. This will let us import from `0-engine` and other top level folders, setting up the eventual module splitting. It will also reduce the import refactoring required when reorganizing folders.

## Acceptance Criteria

# Tasks
```
Use this section to keep track of work
```
- [x] Change tsconfig to handle absolute imports to the top level layer folders. This probably involves `baseUrl` and possibly the `paths` option. -- didn't ned `paths`
- [x] Check if any of the linting plugins need to get these settings also.
- [x] Update all references to a layer from outside the layer with absolute path imports.

# QA Notes
