### ISSUE TITLE
Simplify EntityManager component accessors to have a single generic parameter

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#115]
# Description
In DataDbCmpt, we managed to get a class and its constructor as a generic with only one generic parameter. Let's investigate if such a pattern is usable in EntityManager's component accessor functions. If so, let's use them.

## Acceptance Criteria

# Tasks
```
Use this section to keep track of work
```
- [x] Use a single param in ComponentManager and EntityManager.GetComponent
- [x] Fix any downstream uses of two generic params
- [x] Do the same fix for EntityManager.GetSystem
 
# QA Notes
