### ISSUE TITLE
Shorten, improve, and expand methods on EntityManager

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#130]
# Description
Let's carefully design the methods exposed on EntityManager.
- Method names should be short while minimizing abbreviations
- Let's create separate methods for getting mutable and immutable (readonly) references. Let's use typescript things (like `readonly`) if they make sense

## Acceptance Criteria

# Tasks
```
Use this section to keep track of work
```
- [x] Decide on new methods and names (see below)
- [x] Implement new methods and names on ComponentManager
- [x] Implement new methods and names on EntityManager
- [ ] Investigate adding `readonly` descriptors and similar to actually enforce immutability.

#### New Methods and Names
ComponentManager will have:
- Component Accessors
    - get
    - getMut
    - tryGet
    - tryGetMut
- Component mut
    - add
    - remove
    - has
- Meta
    - count

EntityManager will have:
- Component Manager accessors
    - getMgr
    - getMgrMut
    - tryGetMgr - gets or creates cmpt mgr
    - tryGetMgrMut - gets or creates cmpt mgr
- Component Accessors
    - getCmpt
    - getCmptMut
    - tryGetCmpt
    - tryGetCmptMut
- More Component methods
    - addCmpt - let's have this pass variadic params to constructor if possible
    - removeCmpt
    - getUniqueCmpt
    - getUniqueCmptMut
- System Accessors
    - getSys
- Entity Methods
    - createEntity
    - queueEntityDestruction

# QA Notes
