### ISSUE TITLE
Refactor frontend to use new react-ecsal useSelector

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#133]
# Description
Let's refactor the `useSelector` calls in the frontend to use the new react-ecsal layer. Any data that is copied from the engine in an `update...FromEngine` method using `useUILoop` should be removed from redux.

Let's not update the `dispatch` calls just yet as there isn't much benefit in switching to the react-ecsal dispatch.

## Acceptance Criteria

# Tasks
```
Use this section to keep track of work
```
- Convert `update...FromEngine` uses to use Ecsal's `useSelector`
    - [x] player inventory
    - [x] combatLog
    - [x] towns
    - [x] itemClasses
    - [x] townLocations
    - [ ] ~~units during combat~~ This is too complicated, refactor can occur when the combat is being worked on.
    - [x] do a final pass through the frontend folder for any dead code
- [x] Add DeepReadonly for all read-only access from ComponentManager and EntityManager
- [x] Finish necessary ecsal behavior in GameManager: call all `storeSubscribers` after each `OnUpdate`

# QA Notes
