### ISSUE TITLE
Create arrow component

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#16]
Let's create an arrow for the combat UI. When assigning the target for a unit, an arrow should be drawn from the unit to its potential target.

See: https://github.com/sasza2/arrows

## Tasks
- [X] Get a basic arrow svg component displaying
- [x] generate id instead of "markerArrow". Can just increment global counter for now instead of uuid
- [x] get coords from one end from center of element
- ~~[ ] get coord for the other end from mouse position. Get mouse coords by passing function to onMouseMove to parent element.~~ Going to make detecting mouse position its own issue.
