### ISSUE TITLE
Detect ground clicks in Colosseum

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#165]
# Description
Let's assign one of the circles to be the player character, and add click-to-move controls for it.

## Acceptance Criteria

# Tasks
```
Use this section to keep track of work
```
- [x] Differentiate between the player and enemies by color
- [x] Add another enemy
- [x] Add Ground component in three js scene that can detect ground clicks
    - [x] Ground clicks should not be triggered when something above the ground is clicked.
- [ ] ~~Let the player control the player unit via point & click move mechanics~~ Moved out to #182

# QA Notes
