### ISSUE TITLE
Add proper mouse tracking for ArrowFromUnit

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#18]
Let's track the mouse position in the redux state via a hook.

### Tasks
- [x] Remove/clean up previous attempt at mouse tracking
- [x] Create a ~~hook~~ listener that tracks the mouse's position relative to a container. This could be done in one of two ways:
       - ~~Add onMouseMove to the window, get the pageCoords, and adjust by the container's boundingRect~~
       - Add onMouseMove to the container (div with position: relative) and adjust by the bounding rect there.
       - See the second response (high votes but not accepted): https://stackoverflow.com/questions/16154857/how-can-i-get-the-mouse-coordinates-relative-to-a-parent-div-javascript
- [X] Throttle redux action for mouse tracking
- [X] Link up this state with ArrowFromUnit so the arrow correctly follows the mouse around.
