### ISSUE TITLE
Turn controllers into functions

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#189]
# Description
Let's replace controllers with action creators. Since we have a file listing all the controllers anyway (ControllerList), let's remove the decentralized registration stuff and make a simple dictionary that links all the routes to their handlers.

## Acceptance Criteria

# Tasks

```
Use this section to keep track of work
```
- [ ] Create an action creator helper function similar to redux's `createAction` so we don't have to directly handle constants
- [ ] Replace controllers with the action creator functions
    - [ ] Replace ControllerList with a straight dictionary listing where keys are routes and values are arrays of handler functions
- [ ] We should try to reduce `any`s, such as the one for the data passed to controllers if possible

# QA Notes
