### ISSUE TITLE
Add fireball (aoe attack)

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#19]
Let's add AOE attacks. Enemies on either side of the targeted enemy are also targeted (and indicate such on hover). These enemies are affected by the attack.

### AC
Let's make sure the AOE radius is variable (1 to each side, 2 to each side, etc.)

### Tasks
- [X] Allow selection of actions in action bar. Switch between attack and fireball.
- [X] Generalize minimum logic in AttackSys to allow for fireball and attack actions (allow aoe attack, allow attack logic to utilize different data for attacks).
- Maintain unit order
  - [X] Add CombatPositionCmpt
  - [X] Use CombatPositionCmpt in redux to set the unit position
- [X] Create fireball attack with radius 1
- ~~[ ] Show targeting with AOE radius (UI)~~ split into separate ticket
