### ISSUE TITLE
Make a button to spawn enemies

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#194]
# Description
Let's create a button to spawn enemies. Enemies should have the necessary Components. Extract common logic from Player.

## Acceptance Criteria

# Tasks

```
Use this section to keep track of work
```
- [ ] Create a button in the UI
- [ ] Create a controller path to spawn an enemy in the Colosseum with empty Sys logic
- [ ] Create the function to spawn enemies
- [ ] Refactor common logic with character creation
- [ ] Display enemies in the frontend

# QA Notes
