### ISSUE TITLE
Right click on enemies to attack them

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#195]
# Description
Let's let the player attack enemies.

## Acceptance Criteria

# Tasks

```
Use this section to keep track of work
```
- [ ] Add `range` to an existing component or create a new one
- [ ] Create controller pathway to attacking enemies
    - Reuse existing logic from old combat scene if applicable
- [ ] Attacking should include moving toward the enemy if out of range

# QA Notes
