### ISSUE TITLE
Update and link up the fireball action

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#198]
# Description
Let's port the fireball action to work in the new combat scene and hook it up.

## Acceptance Criteria

# Tasks

```
Use this section to keep track of work
```
- [ ] Update action bar to show fireball somehow
- [ ] Clicking on the fireball button and then the enemy should trigger the correct controller route
- [ ] Detect the fireball and display in the UI
- [ ] Create red circle animation for fireball exploding

# QA Notes
