### ISSUE TITLE
Allow self/ally targeting of skills

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#20]
Let's let all skills target both allies and enemies.

Self-target only skills should skip the targeting indicator. E.g. when you click on "stealth" in the action bar, it should immediately fire the action.

### Tasks
- [x] Add logic to skills that specifies whether it's self-target only or can target other entities. May require significant refactoring.
- [ ] Add logic to UI that follows new targeting logic. Targeting UI is split based on the targeting mode of the skill.
- [x] Implement heal skill
