### ISSUE TITLE
Add stealth skill (and untargetable status effect)

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#21]
Let's add a hide/stealth skill.

### Tasks
- ~~[ ] Port over StatusEffectCmpt implementation from Unity~~Moved to #46.
- [x] Add stealth to status effects
- [x] Add a stealth skill
- [x] Get stealth into redux
- ~~[ ] Add logic to determine whether selectedAction by selectedUnit can target a given unit on hover (will need to work for stealth and enemy/friendly targetable skills)~~ Moved to #20.
- [x] Add untargetable functionality in the UI
