### ISSUE TITLE
Design combat system

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#22]
Let's design the combat system basics. A particular focus is what sort of system we want for scheduling actions. See PoE, BG2, and LoL for implementations of attack speed, animation speed, spell channeling, interrupts, and such.

### Tasks
- [x] Research possible approaches
- [x] Design a simple, effective, powerful system without redundancies.
- [x] Design UI for system (timers above units?)

## References
Summary:
- Simpler is better (BG2 and LoL over PoE)
- Additive attack speed bonuses are much easier than multiplicative
- A hard attack speed cap prevents edge cases, but an easily reached cap strangles build diversity.
- Spells usually have a cast time and may or may not have a recovery time like attacks

### Baldur's Gate 2
Most characters have 1 attack per round (APR). APR may be increased by certain classes (Monks get up to 4 APR when unarmed, Warriors get up to 3 APR with a proficient weapon), buffs, equipment enchantments, and dual wielding. The APR cap is 5.

Spells have a cast time. They have no cooldown, but limited uses per encounter/rest. Generally, mages have high burst, but when they use up all their spells their options decrease dramatically. Cast time caps the speed of the burst.

### Pillars of Eternity
System seems complicated.
Attacks have 3 phases:
- Attack phase (shortened only by dexterity)
- Recovery (affected by most "attack speed" buffs and debuffs)
- Reload - only for ranged weapons

Maximum attack speed is achieved by getting down to 0 recovery and having high DEX, so attack phase is short and recovery phase is skipped. This is easiest to achieve via dual wielding, but can be achieved by many other setups.

An important consideration is the "full attack" mechanic in PoE. Many skills use damage from both wielded weapons, so 1H + nothing and 1H + shield have a significant drawback.

Spells have both cast time and recovery time. 

### League of Legends
Champions start with a certain attacks per second (AS). AS can be increased by levels as the champion levels up, items, and buffs. The AS cap is 2.5.

Skills and spells may have a channel time. They also have cooldown times which may be reduced by items, buffs, and skills.

### Rimworld
All attacks have a cooldown based on the weapon and material. 

**Animation Time:** All weapons have an identical animation time which is not included in available DPS calculations. Short cooldown weapons may have significantly lower DPS due to the impact of animation time.
**The First Attack:** Ranged weapons have a warmup period (aiming time) before they can fire their first shot. Melee weapons' first attack occurs immediately.

### Dwarf Fortress
Attack speed mechanics are currently unclear. Attacks are believed to have a wind-up time and a recovery time. These are modified by the type of attack and the attacker's agility stat.

## Designed System
- Units have an Attacks per Second stat (AS)
- Capped at 2 attacks per second
- All bonuses are additive
- AS is converted to seconds between attack. This is used as a recovery period in between attacks.
- For now, we'll let animation time work however is easiest (likely UI-only, so animation time won't affect DPS)

## UI
- Let's show a cooldown bar for recovery time #32 #34
- Let's show cast/prep/channel time by filling up the cooldown bar with a different color #33 #34
- Let's show a health bar #31
- Let's show a mana bar under the health bar #29 #30
- ~~Let's show status effect text above the health bar (see LoL UI)~~ Split into separate arc: nmkataoka/adv-life#35
- Let's create a sidebar info menu that shows the stats of the selected unit #36
