### ISSUE TITLE
Voronoi Diagrams

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#223]
# Description
Let's get voronoi cell generation for the tectonic plates up. ~~Let's also generate an SVG to display them.~~ Let's skip rendering the voronoi cells unless it becomes necessary for debugging.

## Acceptance Criteria

# Tasks

```
Use this section to keep track of work
```
- [x] Use d3-delaunay to generate a voronoi diagram
- [x] Should be able to control the # of points
- [ ] ~~Add cylindrical option~~ Let's leave this off for now.
- [ ] ~~Render via svg, canvas, d3, or other (can always rasterize into image)~~ Let's leave this off for now.
- Ended up folding #225 and #228 into this ticket for convenience and efficiency.

# QA Notes
