### ISSUE TITLE
Create pure noise subsitute for terrain generation

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#233]
# Description
For debugging and modularization purposes, let's create a substitute for the whole terrain generation process that just uses noise. In the future, we'd like to be able to only run specific world gen modules (e.g. rainfall but not terrain generation).

## Acceptance Criteria

# Tasks

```
Use this section to keep track of work
```
- [x] Use canvas and ImageBitmap to render the world map
- [x] Create or use an engine data structure to store world map elevations. Think carefully about the datatype (probably a typed array is warranted). This should play well with the ImageBitmap renderer if possible
- [x] Find a simplex noise generator
- [x] Noise the elevation map
- [x] Choose some decent colors. We'll do more in depth visuals later

# QA Notes
