### ISSUE TITLE
Create createSys function like createSlice

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#236]
# Description
Let's add a convenience function createSys that has a similar signature and functionality to createSlice from Redux Toolkit (minus the state bits). Let's also create a createPassthrough function to create controller methods that very simply expose an underlying engine Event to the api.

## Acceptance Criteria

# Tasks

```
Use this section to keep track of work
```
- [x] Design and create createEventListener helper methods
- [x] Update EventListener, EventCallback, EventSys and similar to handle new behavior
    - EventHandlers will now receive their component managers or View as an argument instead of having to fetch them themselves. Somewhere upstream will have to fetch these
    - [x] Make sure individual types for the component managers (or components for View) make it all the way through
    - [x] Use ComponentDependencies and type inference instead of referring to ReadCmpts, WriteCmpts, WithoutCmpts in EventCallback and EventListener
    - [x] Convert View to use ComponentDependencies instead of ReadCmpts, WriteCmpts, WithoutCmpts for types
    - [x] Convert all ECSystems away from ECSystem and into simple createListeners
        - This will require making a central file that imports all the listeners, basically a replacement for SystemsList.ts
        - [x] Change Start and OnUpdate to be Events
        - [x] Decide whether createEventListener should create event names. Make appropriate changes
        - [x] Import event listeners directly instead of registering via ECSystems
- [ ] ~~Create createAPIRouteFromEvent method~~ Moved out to #257
- [ ] ~~Convert all relevant api methods to use api passthrough creator~~ Moved out to #257
- [x] Create and update engine tests
- Go through a final cleanup of 
    - [x] folder structure
    - [x] Remove exports that shouldn't be exported. Export from as high as possible when they are needed.
    - [x] code organization
    - [x] types (don't specify types that are automatically inferred)
    - [x] code
- [x] Remove old EventSys code
- [ ] ~~Create other RTK-style helper functions if useful~~ This is enough for now

# QA Notes
