### ISSUE TITLE
Design attack/armor system.

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#24]
Let's design a simple 3 damage type attack/armor system.

### Tasks
- [ ] Research other implementations
- [ ] Design our system
- [ ] Decide on names for the damage and armor types
- [ ] Design UI to communicate which damage types/armor types a unit has.
