### ISSUE TITLE
Implement attack/armor system

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#25]
Let's implement the system in nmkataoka/adv-life#24.

### Tasks
- [ ] Create any components necessary
- [ ] Figure out where the damage/armor types will be matched up during attacks and implement.
- [ ] Add to UI
