### ISSUE TITLE
Add click & drag movement to world map

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#263]
# Description
Let's add click & drag movement to the world map.

## Acceptance Criteria

# Tasks

```
Use this section to keep track of work
```
- [x] Add onMouseUp, down and move events
- [x] Try using canvas context.translate since that seems like the minimum code and it'll merge scaling and translation for us
- [x] Redraw the canvas when drag changes
- [x] Refactor into a hook or useWorldMap
- [x] Clamp the y translation
- [x] Clamp the X translation
- [x] Fix scaling bug -- if you zoom far in and then back out the map ends up super zoomed out even though scale = 1
    - [x] Double check that the canvas transform scale matches the scale in React state -- it's possible that they're getting out of sync due to having 2 sources of truth. If so, we should probably reset the transform and set transform/scale entirely each time rather than incrementally
- [x] Change drawImage to be throttled instead of debounced

# QA Notes
