### ISSUE TITLE
Flesh out city generation on world map

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#264]
# Description
Let's flesh out city generation on the world map. For now, we can use a list of names to randomly choose from, and make sure they are 1) on land and 2) don't overlap. Keep in mind that in the future city placement will be more complex. They can all have identical shops in them for now.

## Acceptance Criteria

# Tasks

```
Use this section to keep track of work
```
- [x] ~~Get a list/way to randomly generate city names~~ Spun out into #433
- [x] Randomize rain layer: #440
- [x] Display rain layer: #444
- [x] Generate starting population distribution: #441
- [x] Display population layer #447
- [ ] Add reproduction based on food supply #446
- [ ] Generate initial towns: #442
- [ ] Generate initial routes: #443
- [ ] Add city (civ?) generation tab to world gen
- [ ] Randomly generate city locations
    - [ ] Let's randomly assign population for now
- [ ] Create a non-scaling HUD layer over the world map
- [ ] Add cities to HUD layer over world map
- [ ] Clicking (hovering over?) a city should make its info appear somewhere
    - [ ] Name
    - [ ] Population
    - [ ] Location

# QA Notes

**Comment by nmkataoka** [comment]
Updating this parent ticket is no longer providing benefits, so I'm closing it. To see all tickets involved with city generation on world map, just look at the tickets under this milestone (Crafting & Trading).
