### ISSUE TITLE
Add targeting indicator

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#27]
Right now only the selected unit is indicated (via outline). Let's add a UI indicator when hovering over valid skill targets.

### Tasks
- [x] Decide on the css for valid skill targets.
  - Let's do cursor: a blue outline. Let's change selected outline to green.
- [x] Implement for single target
- [x] Make this and arrow only appear if action is selected
- ~~[ ] Implement for AOE multitarget~~ Let's not for right now. Too hard.
