### ISSUE TITLE
Refactor backend-api to use middleware, thunks

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#280]
# Description
Instead of having this extra heavy middleware backend layer, let's add the equivalent of redux middleware and thunks.

Note: I tried copying over redux's middleware/store enhancer implementation, but the types involves were super complicated. Hardcoding thunk behavior into entity manager was just a few lines of code, so switched to that implementation.

## Acceptance Criteria

# Tasks

```
Use this section to keep track of work
```
- [x] Implement thunks in the most basic manner
  - [x] Add test for thunks on EntityManager
  - [x] Create a userid or auth middleware to account for how userid is parsed
- [x] Re-implement backend-api as thunks
- [x] Remove Router
- [x] Fix up references to backend-api all the way to the frontend

# QA Notes
