### ISSUE TITLE
Create mana system and add fireball to it

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#29]
Let's create the mana system and update fireball.

- Units have mana
- Mana regenerates slowly over time
- Spells cost mana

### Tasks
- [x] Create ManaCmpt
- [x] Add ManaCmpt to units
- [x] Add a ManaRegeneration system
- ~~[ ] Give spells a mana cost. For now, we can simply add mana cost to the skill data object.~~ Attacks and spells are hardcoded in a switch statement in AttackSys.
- [x] Cause spells to use mana in AttackSys
- [x] Add mana consumption to fireball
