### ISSUE TITLE
Add attack speed (recovery time) between attacks

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#32]
Let's add a cast time and recovery time to actions. Adding recovery time is the same as adding attack speed.

- Units have an attack speed between 0 and 2
- Attack speed may be buffed additively up to 2 (not a near-term feature)
- Attack speed is translated into a recovery time in between attacks. Currently, this recovery time is also used for any spells cast.

### Tasks
- [x] Make a CombatStatsCmpt with attack speed and mana
- [x] Give units a base attack speed
- [x] Make units wait between attacks according to the cooldown period calculated off of attack speed
