### ISSUE TITLE
Display useful calculated stats during world gen

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#327]
# Description
Let's add some useful numbers to the world gen UI. This includes calculated information in the settings pre-generation, and information about the world post generation.

Settings information:
- [ ] Maximum possible altitude (add it all up)
- [ ] Minimum possible altitude
- [ ] Possibly generate warnings. For example, from tecplates, ridge slope, and map size, predict whether fault feature placement will be an issue.

Generated world stats:
- [x] Maximum and minimum altitude
- [ ] Maximum hilliness
- [x] Percentage of world in each altitude "slice" (underwater, low: 0-1500, medium: 1500-3000, high: 3000+)
- [ ] Report if there was an issue placing faults

## Acceptance Criteria

# Tasks

```
Use this section to keep track of work
```

# QA Notes

**Comment by nmkataoka** [comment]
We'll go with just a bit of elevation statistics for now. If we find we need more statistics, we can add them later.
