### ISSUE TITLE
Add recovery/cast time bar (UI)

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#34]
Let's add the recovery/cast time bar to the UI.

### Tasks
- [x] Get channel progress into redux state for units
- [x] Get recovery progress into redux state for units
- [x] Create a bar below the mana bar.
- [x] Fill the bar with ~~blue~~yellow while channelling a spell
- [x] Decrease the bar with gray while recovering from an action.
