### ISSUE TITLE
Tune hydrology params and debug

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#377]
# Description
Let's continue where we left off in #356 and finish up the hydrology system. We stopped work during #356 due to needing to add proper state reconciliation between the ECS system and the React connector.

## Acceptance Criteria

# Tasks

```
Use this section to keep track of work
```
- [x] Finish tweaking params so that erosion is visible. The main params that haven't been tuned yet:
    - [ ] Max velocity (realistic is 5 m/s, right now it goes up to 10-13 m/s)
        - Didn't check the final max velocity, but I don't really care. It's probably still high. Terrain looks good
    - [x] Scale the erosion so it visible affects the heigh map to reasonable amounts
    - [x] Height (volume) of the drop.
    - [x] Running fast with a large number of drops
- [x] Debug

# QA Notes
