### ISSUE TITLE
Add pausing

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#40]
Let's add pausing.

### Tasks
- [x] Create a toggleable pause indicator in the UI
- [x] Add pausability in engine
- [x] Add pause in redux state 
- [x] Add spacebar to keydown listener and trigger pause from it
