### ISSUE TITLE
Make different icons for cities based on their population

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#419]
# Description
Let's use standard icons for cities based on population. Basically larger/concentric circles for larger cities. See: https://www.mapdiva.com/ortelius/ortl-tutorial/symbolizing-cities-and-towns-on-small-to-medium-scale-maps/

![Screen Shot 2021-05-21 at 12 15 04 AM](https://user-images.githubusercontent.com/10602320/119081276-a99aed80-b9c9-11eb-904b-49ece5facfb0.png)

Let's start by using the first three icons. We should be able to make these svgs, if we can't then that would be very sad. Probably can even do it in VSCode since it's just `<circle>` components. Later on we probably will want a fourth icon for capitals.

## Acceptance Criteria

# Tasks

```
Use this section to keep track of work
```
- [x] Create village map symbol (literally a dot)
- [x] Create town map symbol (circle with 2 concentric rings of alternating colors)
- [x] Create city map symbol (circle with 3 concentric rings of alternating colors)

# QA Notes
