### ISSUE TITLE
Generate initial towns

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#442]
# Description
Let's generate the initial towns based on the population distribution in #441.

Need to somehow allow towns to draw food from surrounding area.

After more thought, considering the following:
- Good video: https://www.youtube.com/watch?v=3PWWtqfwacQ
- Majority of land should be unpopulated in ancient period to Middle Ages, especially in our fantasy world

Lets do this:
- Axe the population map. Towns will track population
- Let's seed a single town (in the future, individual races/civs can seed towns)
- Once a town's pop reaches the cap, it searches for a place to put a new town
    - For now, we can just randomly pick a place nearby. In the near future this should follow rivers, coasts, roads, and food supply
    - Towns should be stored in some sort of graph structure
    - Probably the civ as a whole should pick places for new towns and track overall excess pop
    - Towns have a radius of influence for drawing food.
    - "Road" (lowest level, footpath) is automatically formed to new towns
    - Radius of influence is affected by fertility of land (food). High fertility = low radius

Future work
- Later on, cities will be towns that get "promoted" and have influence over nearby towns. Promotion is affected by trade and geography
- Form roads between existing towns

Discarded ideas
    - Don't bother simulating town creation every ticket and just distribute points based on a density function, use this: https://stackoverflow.com/questions/9294316/distribute-points-on-mesh-according-to-density

## Acceptance Criteria

# Tasks

```
Use this section to keep track of work
```
- [x] Axe population map in favor of "food" map which is calculated from sunshine, rainfall, and then blurred
- [x] Initialize one civ
- [x] Create/update town and route creation methods

Splitting the rest of the tasks into a new ticket: #505
- [ ] Reproduce pop on each tick
- [ ] Randomly create new towns on each tick if there is excess pop
- [ ] Display towns on map

# QA Notes
