### ISSUE TITLE
Add combat log

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#49]
Let's add a combat log. It should record all the actions taken by combatants and associate a unique id with each action. We can add a combat log window in the UI.

This will allow us to fix a bug with the damage animation logic #50.

### Tasks
- [x] Do any necessary refactoring of EventManager (now EventSys), actions
- [x] Dispatch event on attack
- [x] Create CombatLogSys that records all combat events
- [x] Get combat log into redux
- [x] Create UI textbox with overflow scroll that shows all combat logs
- [x] Dispatch event on other combat actions
