### ISSUE TITLE
Display civ scene and towns on world map

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#505]
# Description
Let's have towns/civs update on tick as stated in tasks.

## Acceptance Criteria

# Tasks

```
Use this section to keep track of work
```
- [x] Reproduce pop on each tick
- [x] Add Civ scene
    - [x] Add a button to save world and go back to main menu
    - [x] Update colors to theme colors
    - [x] Refactor characterCreationSlice to handle dynamic civ data...but not too much
    - [x] Start player as civ ruler in game and allow them to open up the civ management scene
    - [x] Display towns on map
    - [x] Fix town icon
    - [x] Trigger turns through a UI interface like Civ turn based
    - [x] See what can be shared between WorldMap, WorldGen Map, and Civ Map
        - [x] Map should hold shared code like the Political layer while individual maps can have their own overlays (added via children), like the civ Next Turn button and the world gen overlay
        - [x] We probably need a map context to allow custom overlays access to map data. Or...just have custom overlays read straight from engine? Caching should be able to handle this.
    - [ ] Get town placement on map correct (including zoom) - spinning this out into #512 since it'll be easier to judge position with multiple towns
- [ ] Randomly create new towns on each tick if there is excess pop - spun out into #512

# QA Notes
