### ISSUE TITLE
Add town info and on hover state

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#524]
# Description
Let's display some town stats and add nice on hover visuals to towns in the world map/civ map.

## Acceptance Criteria

# Tasks

```
Use this section to keep track of work
```
- [x] Add an info window to CivScene. Let's make this a vertical flex box
- [ ] ~~Let's make an Info context which accepts a React component (unrendered) and props. Not sure if passing the component through a context is the best method but it seems okay.~~ 
    - [x] Let's use a portal as is appropriate. In order to guarantee only one thing is displayed in the info window at a time, let's:
    - [x] Put this in redux, cuz it doesn't really matter
    - [x] Have components register and receive an id. If the info id matches the component id, then it owns the info box and can display its info through a portal
    - [x] Scenes are responsible for placing the portal root.
    - [ ] ~~Let's also make sure to clear the info state on scene change~~ This is unnecessary since each scene should have its own info context, so changing scenes should already clear the context.
    - [x] Add default info window element
- [x] Refactor character creation scene to use this info reducer
- [x] Add on hover visuals to the town on the world map
- [x] On click, update info in info window. 

# QA Notes
