### ISSUE TITLE
Add serialization

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#531]
# Description
Let's add a serialization feature to the engine. Since 100% of state should be contained within components, we should be able to use the static parent method on NComponent for deserialization and json.stringify for serialization.

## Acceptance Criteria

# Tasks

```
Use this section to keep track of work
```
- [ ] Add a `serialize` method to `EntityManager` that calls `JSON.stringify` on all component managers
    - [ ] Check carefully that versioning is preserved correctly
- [ ] Create a `serializable` decorator that will register component classes with the deserializer
- [ ] Add a `deserialize` method to `EntityManager` that calls deserializer
    - [ ] Consider using TypedJSON...but probably only as inspiration, it seems easy enough to do it ourselves from scratch

# QA Notes
