### ISSUE TITLE
Make town base scene

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#64]
# Description
Let's create a "town" scene.
## Acceptance Criteria

# Tasks
```
Use this section to keep track of work
```
- [x] Create a town scene
- [x] Create a modal component
- [x] Add several "shops" to the town scene that open up empty modals when clicked on

# QA Notes
