### ISSUE TITLE
Make world map

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#65]
# Description
Let's create a world map modal. Locations such as combat encounters and a town should be visible. You should be able to transition between the world map and the town.

## Acceptance Criteria

# Tasks
```
Use this section to keep track of work
```
- [x] Create world map UI
- [x] Add a button to the navbar that opens the world map
- [x] Add a town location. Clicking on the location should go to the town
- [x] Add hardcoded combat locations. These don't have to do anything yet

# QA Notes
