### ISSUE TITLE
Add basic equipment system

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#69]
# Description
Let's add the minimum features to get an equipment system.

- Weapons
- Armor
- Ability to equip equipment from inventory

## Acceptance Criteria

# Tasks
```
Use this section to keep track of work
```
- Engine Content
    - [x] Add item ncomponents
    - [x] Add InventoryCmpt
    - [x] Add shops
    - [x] Generate two towns with shops on game start
    - [x] Set up gold system, interface, and give player starting gold
    - [x] Create necessary engine-ui actions so player can buy equipment
    - [x] Create necessary engine-ui actions so player can equip items
- UI
    - [x] Add inventory screen skeleton
    - [x] Hook up world map to go to actual towns
    - [x] Hook up TownScene to show actual town data, (name and shops)
    - [x] Hook up TownLocation to show actual shop inventory when clicking on it
    - [x] Hook up shop inventory to let player buy items
    - [ ] ~~Hook up player inventory so player can equip items~~ Going to split off into a separate ticket

# QA Notes
## Steps

# Pull Requests
https://github.com/nmkataoka/adv-life/pull/89
