### ISSUE TITLE
Add combat encounters to the world map

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#72]
# Description
Let's add combat encounters to the world map.

## Acceptance Criteria

# Tasks
```
Use this section to keep track of work
```
- [ ] Add hardcoded combat locations to the world map. Randomization will come later
- [ ] Clicking on a combat location should enter the combat scene with hardcoded enemies.
- [x] Game should know if you're in combat so you can't just run away. Game should detect victory
- [ ] Losing should send the player to a lose screen overlay, which for now can just show "Your party has fallen." The user can refresh the page to restart.

# QA Notes

**Comment by nmkataoka** [comment]
#47 needs to be finished before the game can properly use `UnitInfo.targetEntity` to determine if the party is still in combat. So we'll switch to just checking if any enemies are still alive.

**Comment by nmkataoka** [comment]
We need some more functionality before the tasks on this ticket can fully be implemented. I've added scaffolding for as much as I could and spun out tickets for the rest.
