### ISSUE TITLE
Create webpage

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#73]
# Description
Let's make the default page an actual web page and move the "game" app component to a new spot. Let's lazy load the app.

## Acceptance Criteria

# Tasks
```
Use this section to keep track of work
```
- [ ] Move the current root "app" page to a new component
- [ ] Create a new minimal homepage
- [ ] Use React.lazy to dynamically import the game
- [ ] Use a library like NProgress to create a loading bar or animation

# QA Notes
