### ISSUE TITLE
Deploy to s3 automatically

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#74]
# Description
Let's push the webpage to s3 using Github actions.

## Acceptance Criteria

# Tasks
```
Use this section to keep track of work
```
- [ ] Set up s3 buckets and policies
- [ ] Create a prod version branch
- [ ] Using Github actions, automatically deploy prod to the s3 bucket
- [ ] Automatically deploy master to another s3 bucket

# QA Notes
