### ISSUE TITLE
Set up website

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#75]
# Description
Let's set up the actual website using the s3 bucket set up in #74.

## Acceptance Criteria

# Tasks
```
Use this section to keep track of work
```
- [ ] Decide if we want a new domain name or a subdomain of leatherbee.org. `adventurers-life.com` seems to be the only obvious one available.
- [ ] Connect the s3 buckets to cloudfront
- [ ] Connect the domain to cloudfront

# QA Notes
