### ISSUE TITLE
Character Creation

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#79]
# Description
Let's add a character creation screen.

## Acceptance Criteria

# Tasks
```
Use this section to keep track of work
```
- [x] Create a character creation scene
- [x] Randomize all characteristics
- [x] Provide inputs for all the characteristics
- [x] Add a button to start the game
    - [x] Should go to the Town scene
- [x] Create the player entity and assign the player entity handle in redux

# QA Notes
