### ISSUE TITLE
Trigger garbage collection during idle times

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#92]
# Description
Let's try controlling some of the garbage collection to reduce garbage-collection freezes.

References:
https://v8.dev/blog/free-garbage-collection

## Acceptance Criteria

# Tasks
```
Use this section to keep track of work
```
- [ ] Check if there have been any updates in v8 / Node garbage collection. For example, see if fully concurrent garbage collection exists yet, or if node has exposed any additional GC functionality
- [ ] Change the run script to run with flag `--expose-gc`
- [ ] In the game loop, when calculations are done with enough time to spare, trigger the garbage collector
    - May need to refactor or create a task scheduler here

# QA Notes
