### ISSUE TITLE
Bump react-scripts to version 4.0

### ISSUE THREAD

**Issue by nmkataoka** [nmkataoka/adv-life#96]
# Description
When react-scripts 4.0 is released, let's bump it. This will allow several other updates that can occur in this ticket.

It's close: https://github.com/facebook/create-react-app/milestone/69

## Acceptance Criteria

# Tasks
```
Use this section to keep track of work
```
- [x] Bump react-scripts to version 4.0
- [x] Update all eslint-related packages, as react-scripts is updating eslint a major version here
- [x] Upgrade Typescript: https://github.com/facebook/create-react-app/milestone/69
- [x] Upgrade React to 17
- [ ] ~~Try removing the "deprecation" package in eslint config and see if the jsdoc `/** @deprecation */` comments still work. If they do, let's uninstall the eslint package for deprecation.~~ This seems to already have been done.
- [x] Fix everything that broke

# QA Notes
